### ISSUE TITLE
Playdate OS 2.0 Error e4

### ISSUE THREAD

**Issue by BolvdoK** [jaames/playnote-studio#15]
Recently received my Playdate. I tried running Playnote build 1.1 from the website, but I get error e4 as the build is incompatible with the newer system OS 2.0 update. I'm currently at Playdate OS 2.0.3.

**Comment by Obspogon** [comment]
same here

**Comment by jobukkit** [comment]
I recompiled it for 2.0.3. [Playnote.pdx.zip](https://github.com/jaames/playnote-studio/files/12715000/Playnote.pdx.zip)

**Comment by BolvdoK** [comment]
@jobukkit The build works perfectly :) thank you.
